package com.sirding.mybatis.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table app_menu
 *
 * @mbg.generated do_not_delete_during_merge Tue Oct 18 23:45:29 CST 2016
 */
public class AppMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.id
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   上级菜单的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.parent_id
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.name
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    private String name;

    /**
     * Database Column Remarks:
     *   菜单对应的连接地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.url
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    private String url;

    /**
     * Database Column Remarks:
     *   菜单显示的位置 1：前台 2：后台
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.pos
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    private Byte pos;

    /**
     * Database Column Remarks:
     *   描述信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.note
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_menu
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.id
     *
     * @return the value of app_menu.id
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.id
     *
     * @param id the value for app_menu.id
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.parent_id
     *
     * @return the value of app_menu.parent_id
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.parent_id
     *
     * @param parentId the value for app_menu.parent_id
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.name
     *
     * @return the value of app_menu.name
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.name
     *
     * @param name the value for app_menu.name
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.url
     *
     * @return the value of app_menu.url
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.url
     *
     * @param url the value for app_menu.url
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.pos
     *
     * @return the value of app_menu.pos
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public Byte getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.pos
     *
     * @param pos the value for app_menu.pos
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public void setPos(Byte pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.note
     *
     * @return the value of app_menu.note
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.note
     *
     * @param note the value for app_menu.note
     *
     * @mbg.generated Tue Oct 18 23:45:29 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}