package com.sirding.mybatis.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table app_perm
 *
 * @mbg.generated do_not_delete_during_merge Tue Oct 18 23:45:32 CST 2016
 */
public class AppPerm implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_perm.id
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   角色规则eg:[user:del:1] or [user:del]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_perm.wildcard
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    private String wildcard;

    /**
     * Database Column Remarks:
     *   权限描述信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_perm.note
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_perm.id
     *
     * @return the value of app_perm.id
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_perm.id
     *
     * @param id the value for app_perm.id
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_perm.wildcard
     *
     * @return the value of app_perm.wildcard
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    public String getWildcard() {
        return wildcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_perm.wildcard
     *
     * @param wildcard the value for app_perm.wildcard
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    public void setWildcard(String wildcard) {
        this.wildcard = wildcard == null ? null : wildcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_perm.note
     *
     * @return the value of app_perm.note
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_perm.note
     *
     * @param note the value for app_perm.note
     *
     * @mbg.generated Tue Oct 18 23:45:32 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}