package com.sirding.mybatis.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table app_sys_user_role
 *
 * @mbg.generated do_not_delete_during_merge Tue Oct 18 11:55:32 CST 2016
 */
public class AppSysUserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sys_user_role.id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   系统用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sys_user_role.sys_user_id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    private Integer sysUserId;

    /**
     * Database Column Remarks:
     *   角色id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_sys_user_role.role_id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sys_user_role.id
     *
     * @return the value of app_sys_user_role.id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sys_user_role.id
     *
     * @param id the value for app_sys_user_role.id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sys_user_role.sys_user_id
     *
     * @return the value of app_sys_user_role.sys_user_id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    public Integer getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sys_user_role.sys_user_id
     *
     * @param sysUserId the value for app_sys_user_role.sys_user_id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    public void setSysUserId(Integer sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_sys_user_role.role_id
     *
     * @return the value of app_sys_user_role.role_id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_sys_user_role.role_id
     *
     * @param roleId the value for app_sys_user_role.role_id
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}