package com.sirding.mybatis.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table app_user_role
 *
 * @mbg.generated do_not_delete_during_merge Tue Oct 18 23:45:59 CST 2016
 */
public class AppUserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_role.id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   应用用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_role.user_id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   角色id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user_role.role_id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_role.id
     *
     * @return the value of app_user_role.id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_role.id
     *
     * @param id the value for app_user_role.id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_role.user_id
     *
     * @return the value of app_user_role.user_id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_role.user_id
     *
     * @param userId the value for app_user_role.user_id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_role.role_id
     *
     * @return the value of app_user_role.role_id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_role.role_id
     *
     * @param roleId the value for app_user_role.role_id
     *
     * @mbg.generated Tue Oct 18 23:45:59 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}