package com.sirding.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Double value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Double value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Double value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Double value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Double value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Double> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Double> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Double value1, Double value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Double value1, Double value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andTestaIsNull() {
            addCriterion("TEST_a is null");
            return (Criteria) this;
        }

        public Criteria andTestaIsNotNull() {
            addCriterion("TEST_a is not null");
            return (Criteria) this;
        }

        public Criteria andTestaEqualTo(String value) {
            addCriterion("TEST_a =", value, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaNotEqualTo(String value) {
            addCriterion("TEST_a <>", value, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaGreaterThan(String value) {
            addCriterion("TEST_a >", value, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaGreaterThanOrEqualTo(String value) {
            addCriterion("TEST_a >=", value, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaLessThan(String value) {
            addCriterion("TEST_a <", value, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaLessThanOrEqualTo(String value) {
            addCriterion("TEST_a <=", value, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaLike(String value) {
            addCriterion("TEST_a like", value, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaNotLike(String value) {
            addCriterion("TEST_a not like", value, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaIn(List<String> values) {
            addCriterion("TEST_a in", values, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaNotIn(List<String> values) {
            addCriterion("TEST_a not in", values, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaBetween(String value1, String value2) {
            addCriterion("TEST_a between", value1, value2, "testa");
            return (Criteria) this;
        }

        public Criteria andTestaNotBetween(String value1, String value2) {
            addCriterion("TEST_a not between", value1, value2, "testa");
            return (Criteria) this;
        }

        public Criteria andTestBIsNull() {
            addCriterion("TEST_b is null");
            return (Criteria) this;
        }

        public Criteria andTestBIsNotNull() {
            addCriterion("TEST_b is not null");
            return (Criteria) this;
        }

        public Criteria andTestBEqualTo(Double value) {
            addCriterion("TEST_b =", value, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBNotEqualTo(Double value) {
            addCriterion("TEST_b <>", value, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBGreaterThan(Double value) {
            addCriterion("TEST_b >", value, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBGreaterThanOrEqualTo(Double value) {
            addCriterion("TEST_b >=", value, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBLessThan(Double value) {
            addCriterion("TEST_b <", value, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBLessThanOrEqualTo(Double value) {
            addCriterion("TEST_b <=", value, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBIn(List<Double> values) {
            addCriterion("TEST_b in", values, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBNotIn(List<Double> values) {
            addCriterion("TEST_b not in", values, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBBetween(Double value1, Double value2) {
            addCriterion("TEST_b between", value1, value2, "testB");
            return (Criteria) this;
        }

        public Criteria andTestBNotBetween(Double value1, Double value2) {
            addCriterion("TEST_b not between", value1, value2, "testB");
            return (Criteria) this;
        }

        public Criteria andNameaIsNull() {
            addCriterion("CUST_namea is null");
            return (Criteria) this;
        }

        public Criteria andNameaIsNotNull() {
            addCriterion("CUST_namea is not null");
            return (Criteria) this;
        }

        public Criteria andNameaEqualTo(String value) {
            addCriterion("CUST_namea =", value, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaNotEqualTo(String value) {
            addCriterion("CUST_namea <>", value, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaGreaterThan(String value) {
            addCriterion("CUST_namea >", value, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_namea >=", value, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaLessThan(String value) {
            addCriterion("CUST_namea <", value, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaLessThanOrEqualTo(String value) {
            addCriterion("CUST_namea <=", value, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaLike(String value) {
            addCriterion("CUST_namea like", value, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaNotLike(String value) {
            addCriterion("CUST_namea not like", value, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaIn(List<String> values) {
            addCriterion("CUST_namea in", values, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaNotIn(List<String> values) {
            addCriterion("CUST_namea not in", values, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaBetween(String value1, String value2) {
            addCriterion("CUST_namea between", value1, value2, "namea");
            return (Criteria) this;
        }

        public Criteria andNameaNotBetween(String value1, String value2) {
            addCriterion("CUST_namea not between", value1, value2, "namea");
            return (Criteria) this;
        }

        public Criteria andNamebIsNull() {
            addCriterion("CUST_nameb is null");
            return (Criteria) this;
        }

        public Criteria andNamebIsNotNull() {
            addCriterion("CUST_nameb is not null");
            return (Criteria) this;
        }

        public Criteria andNamebEqualTo(String value) {
            addCriterion("CUST_nameb =", value, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebNotEqualTo(String value) {
            addCriterion("CUST_nameb <>", value, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebGreaterThan(String value) {
            addCriterion("CUST_nameb >", value, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_nameb >=", value, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebLessThan(String value) {
            addCriterion("CUST_nameb <", value, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebLessThanOrEqualTo(String value) {
            addCriterion("CUST_nameb <=", value, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebLike(String value) {
            addCriterion("CUST_nameb like", value, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebNotLike(String value) {
            addCriterion("CUST_nameb not like", value, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebIn(List<String> values) {
            addCriterion("CUST_nameb in", values, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebNotIn(List<String> values) {
            addCriterion("CUST_nameb not in", values, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebBetween(String value1, String value2) {
            addCriterion("CUST_nameb between", value1, value2, "nameb");
            return (Criteria) this;
        }

        public Criteria andNamebNotBetween(String value1, String value2) {
            addCriterion("CUST_nameb not between", value1, value2, "nameb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 20 17:05:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated Tue Sep 20 17:05:07 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}