package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AddresInfo;
import com.sirding.mybatis.model.AddresInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddresInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    long countByExample(AddresInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    int deleteByExample(AddresInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    int insert(AddresInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    int insertSelective(AddresInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    List<AddresInfo> selectByExample(AddresInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    AddresInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") AddresInfo record, @Param("example") AddresInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    int updateByExample(@Param("record") AddresInfo record, @Param("example") AddresInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    int updateByPrimaryKeySelective(AddresInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table addres_info
     *
     * @mbg.generated Sun Oct 16 00:43:03 CST 2016
     */
    int updateByPrimaryKey(AddresInfo record);
}