package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppMenu;
import com.sirding.mybatis.model.AppMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    long countByExample(AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    int deleteByExample(AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    int insert(AppMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    int insertSelective(AppMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    List<AppMenu> selectByExample(AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    AppMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppMenu record, @Param("example") AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    int updateByExample(@Param("record") AppMenu record, @Param("example") AppMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    int updateByPrimaryKeySelective(AppMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_menu
     *
     * @mbg.generated Sun Oct 23 11:29:24 CST 2016
     */
    int updateByPrimaryKey(AppMenu record);
    
    /**
     * 查询应用用户拥有的菜单
     * @date 2016年10月20日
     * @author zc.ding
     * @param id
     * @return
     */
    List<AppMenu> findMenuListByUserId(Integer id);
    
    /**
     * 查询系统管理员拥有的菜单
     * @date 2016年10月20日
     * @author zc.ding
     * @param id
     * @return
     */
    List<AppMenu> findMenuListBySysUserId(Integer id);

}