package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppPerm;
import com.sirding.mybatis.model.AppPermExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppPermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    long countByExample(AppPermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    int deleteByExample(AppPermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    int insert(AppPerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    int insertSelective(AppPerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    List<AppPerm> selectByExample(AppPermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    AppPerm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppPerm record, @Param("example") AppPermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    int updateByExample(@Param("record") AppPerm record, @Param("example") AppPermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    int updateByPrimaryKeySelective(AppPerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_perm
     *
     * @mbg.generated Tue Oct 18 11:55:12 CST 2016
     */
    int updateByPrimaryKey(AppPerm record);
}