package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppRolePerm;
import com.sirding.mybatis.model.AppRolePermExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppRolePermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    long countByExample(AppRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    int deleteByExample(AppRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    int insert(AppRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    int insertSelective(AppRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    List<AppRolePerm> selectByExample(AppRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    AppRolePerm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppRolePerm record, @Param("example") AppRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    int updateByExample(@Param("record") AppRolePerm record, @Param("example") AppRolePermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    int updateByPrimaryKeySelective(AppRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_perm
     *
     * @mbg.generated Tue Oct 18 23:45:44 CST 2016
     */
    int updateByPrimaryKey(AppRolePerm record);
}