package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppRoleMenu;
import com.sirding.mybatis.model.AppRoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    long countByExample(AppRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    int deleteByExample(AppRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    int insert(AppRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    int insertSelective(AppRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    List<AppRoleMenu> selectByExample(AppRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    AppRoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppRoleMenu record, @Param("example") AppRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    int updateByExample(@Param("record") AppRoleMenu record, @Param("example") AppRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    int updateByPrimaryKeySelective(AppRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role_menu
     *
     * @mbg.generated Tue Oct 18 11:55:21 CST 2016
     */
    int updateByPrimaryKey(AppRoleMenu record);
}