package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppRole;
import com.sirding.mybatis.model.AppRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    long countByExample(AppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    int deleteByExample(AppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    int insert(AppRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    int insertSelective(AppRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    List<AppRole> selectByExample(AppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    AppRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppRole record, @Param("example") AppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    int updateByExample(@Param("record") AppRole record, @Param("example") AppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    int updateByPrimaryKeySelective(AppRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_role
     *
     * @mbg.generated Tue Oct 18 11:55:17 CST 2016
     */
    int updateByPrimaryKey(AppRole record);
}