package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppSysUser;
import com.sirding.mybatis.model.AppSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    long countByExample(AppSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    int deleteByExample(AppSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    int insert(AppSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    int insertSelective(AppSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    List<AppSysUser> selectByExample(AppSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    AppSysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppSysUser record, @Param("example") AppSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    int updateByExample(@Param("record") AppSysUser record, @Param("example") AppSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    int updateByPrimaryKeySelective(AppSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user
     *
     * @mbg.generated Tue Oct 18 23:45:47 CST 2016
     */
    int updateByPrimaryKey(AppSysUser record);
}