package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppSysUserRole;
import com.sirding.mybatis.model.AppSysUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppSysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    long countByExample(AppSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    int deleteByExample(AppSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    int insert(AppSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    int insertSelective(AppSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    List<AppSysUserRole> selectByExample(AppSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    AppSysUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppSysUserRole record, @Param("example") AppSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    int updateByExample(@Param("record") AppSysUserRole record, @Param("example") AppSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    int updateByPrimaryKeySelective(AppSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_sys_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:32 CST 2016
     */
    int updateByPrimaryKey(AppSysUserRole record);
}