package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppUserRole;
import com.sirding.mybatis.model.AppUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    long countByExample(AppUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    int deleteByExample(AppUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    int insert(AppUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    int insertSelective(AppUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    List<AppUserRole> selectByExample(AppUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    AppUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppUserRole record, @Param("example") AppUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    int updateByExample(@Param("record") AppUserRole record, @Param("example") AppUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    int updateByPrimaryKeySelective(AppUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_role
     *
     * @mbg.generated Tue Oct 18 11:55:35 CST 2016
     */
    int updateByPrimaryKey(AppUserRole record);
}