package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.AppUserInfo;
import com.sirding.mybatis.model.AppUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    long countByExample(AppUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    int deleteByExample(AppUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    int insert(AppUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    int insertSelective(AppUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    List<AppUserInfo> selectByExample(AppUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    AppUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppUserInfo record, @Param("example") AppUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    int updateByExample(@Param("record") AppUserInfo record, @Param("example") AppUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    int updateByPrimaryKeySelective(AppUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat Oct 15 09:19:30 CST 2016
     */
    int updateByPrimaryKey(AppUserInfo record);
}