package com.sirding.mybatis.mapper;

import com.sirding.mybatis.model.OauthClientDetails;
import com.sirding.mybatis.model.OauthClientDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthClientDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    long countByExample(OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int deleteByExample(OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int deleteByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int insert(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int insertSelective(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    List<OauthClientDetails> selectByExampleWithBLOBs(OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    List<OauthClientDetails> selectByExample(OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    OauthClientDetails selectByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") OauthClientDetails record, @Param("example") OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") OauthClientDetails record, @Param("example") OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int updateByExample(@Param("record") OauthClientDetails record, @Param("example") OauthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int updateByPrimaryKeySelective(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Nov 15 23:57:29 CST 2016
     */
    int updateByPrimaryKey(OauthClientDetails record);
}